[package]
name = "metis-chain"
version.workspace = true
edition.workspace = true

[dependencies]
metis-primitives.workspace = true
metis-pe.workspace = true
revm.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-consensus.workspace = true
alloy-primitives.workspace = true
alloy-evm.workspace = true
alloy-hardforks.workspace = true
alloy-eips.workspace = true

reth.workspace = true
reth-chainspec.workspace = true
reth-evm-ethereum.workspace = true
reth-evm.workspace = true
reth-primitives.workspace = true

eyre = "0.6"
num_cpus = "1.16.0"
